stages:
  - helm_push

build:
  tags:
    - argus
    - docker-image
  stage: helm_push

  variables:
    REGISTRY_FOLDER: gcr.io/diamond-privreg/controls/prod/helm/${CI_PROJECT_NAME}
    CR_TOKEN: $CR_TOKEN
    CR_USER: $CR_USER
    TAG: $CI_COMMIT_TAG

  rules:
    - if: $CI_COMMIT_TAG != null
      variables:
        DO_PUSH: "true"
    - if: $CI_COMMIT_TAG == null
      variables:
        DO_PUSH: "false"

  image:
    name: alpine/k8s:1.25.6
    entrypoint: [""]

  script:
    - sh ./ci_build.sh
