on:
  push:
  pull_request:

jobs:
  verify_ioc_instances:
    runs-on: ubuntu-latest
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: run IOC checks
        run: |
          python -m pip install --upgrade pip ;
          pip install -r requirements.txt ;
          bash ./ci_verify.sh
